### ISSUE TITLE
renku commands auto-completion

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renkulab-docker#108] opened 2020-05-11 13:35 UTC
It would be nice to have auto-completion working for `renku` commands in the images so that the user experience on interactive environments would be better.

It may be just a matter of
```
renku --install-completion
. /home/jovyan/.bash_completion
```

**Comment by rokroskar** [comment] 2020-08-19 21:58
Duplicate of #116

**Closed by rokroskar** 2020-08-19 21:58 UTC
Labels: QA
